"""Supplement Phase 37 P37-A-Q02 R-multiple candidate for third audit.

This script patches the candidate only and exports a single-item third audit
package. It does not create formal reviewed knowledge, approved knowledge,
default guidance, or hard gates.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import date
from pathlib import Path
from typing import Any


CORE_DIR = Path(__file__).resolve().parents[2] / "core"
if str(CORE_DIR) not in sys.path:
    sys.path.insert(0, str(CORE_DIR))

from path_resolver import resolve_repo_path  # noqa: E402


TODAY = date(2026, 6, 11).isoformat()
CANDIDATE_PATH = resolve_repo_path(
    "codex-expert-kit",
    "rag",
    "candidates",
    "KB_01_QUANT_FOUNDATION",
    "cand_20260611_phase37_r_multiple_definition_001.json",
    start_file=__file__,
)
RESEARCH_PATH = resolve_repo_path(
    "docs", "research", "phase37_q02_r_multiple_third_audit_research.md", start_file=__file__
)
AUDIT_PATH = resolve_repo_path(
    "docs", "audit", "phase37_q02_r_multiple_third_audit_package_20260611.json", start_file=__file__
)
QUALITY_PATH = resolve_repo_path(
    "docs", "reports", "phase37_q02_r_multiple_third_audit_quality_gate.json", start_file=__file__
)
REPORT_PATH = resolve_repo_path(
    "docs", "reports", "phase37_q02_r_multiple_third_audit_package_report.json", start_file=__file__
)


ADDITIONAL_SOURCES: list[dict[str, Any]] = [
    {
        "source_title": "Super Trader, Expanded Edition: Make Consistent Profits in Good and Bad Markets",
        "source_url": "https://books.google.com/books/about/Super_Trader_Expanded_Edition_Make_Consi.html?id=5oFMvJcxEeUC",
        "source_type": "book",
        "publisher": "McGraw Hill Professional / Google Books metadata",
        "published_at": "2010-12-10",
        "score": 86,
        "reliability": "high",
        "evidence_summary": (
            "Google Books records Van K. Tharp's Super Trader, expanded edition, with Part 3 on developing a trading "
            "system and Part 4 on position sizing strategies; its indexed terms include R-multiple distribution, "
            "initial risk, expectancy, and trading results."
        ),
        "limitations": [
            "Book metadata and preview index support source provenance; exact page-level verification should be checked by a human auditor before formal reviewed conversion."
        ],
    },
    {
        "source_title": "The Definitive Guide to Position Sizing: How to Evaluate Your System and Use Position Sizing to Meet Your Objectives",
        "source_url": "https://www.amazon.com/Definitive-Guide-Position-Sizing-Objectives/dp/0935219099",
        "source_type": "book",
        "publisher": "International Institute of Trading Mastery / Amazon book metadata",
        "published_at": None,
        "score": 84,
        "reliability": "medium_high",
        "evidence_summary": (
            "Book metadata identifies Van Tharp's dedicated position-sizing work; publisher/author metadata supports "
            "using it as a primary bibliographic source for R, position sizing, and system-evaluation concepts."
        ),
        "limitations": [
            "Metadata is not a substitute for page-level quotation; formal conversion should keep it as bibliographic support unless page references are provided."
        ],
    },
    {
        "source_title": "SQN",
        "source_url": "https://www.tradingview.com/script/vTaMXYEn-SQN/",
        "source_type": "trading_platform_doc",
        "publisher": "TradingView",
        "published_at": "2018-09-19",
        "score": 76,
        "reliability": "medium",
        "evidence_summary": (
            "Explains SQN as relating mean expectancy, standard deviation, trade count, and the R-multiple distribution "
            "generated by a trading system, supporting the risk-normalized performance-metric classification."
        ),
        "limitations": [
            "Community platform documentation; useful as supporting evidence, not sole authority."
        ],
    },
    {
        "source_title": "R-Multiples and Expectancy",
        "source_url": "https://twoquants.substack.com/p/r-multiples-and-expectancy",
        "source_type": "systematic_trader_article",
        "publisher": "Twoquants / Moritz Seibert",
        "published_at": "2023-07-23",
        "score": 78,
        "reliability": "medium_high",
        "evidence_summary": (
            "Defines R-multiple as expressing profit and loss as multiples of initial trade risk, links average "
            "R-multiple to expectancy, and cautions that meaningful R-multiple distributions need large sample sizes."
        ),
        "limitations": [
            "Practitioner article; supports systematic-trading usage and sample-size caveat, but does not replace book or institutional sources."
        ],
    },
    {
        "source_title": "Weekly Newsletter #837",
        "source_url": "https://vantharpinstitute.com/Tharps-Thoughts/837_05_10_2017.html",
        "source_type": "professional_training_note",
        "publisher": "Van Tharp Institute",
        "published_at": "2017-05-10",
        "score": 80,
        "reliability": "medium_high",
        "evidence_summary": (
            "Van Tharp Institute newsletter metadata points to expectancy, position sizing strategies, and the power "
            "of big R-multiples through simulation training."
        ),
        "limitations": [
            "Some mirrors include tracking parameters and page availability can vary; auditor should verify access."
        ],
    },
]


PATCH_NOTES = [
    "将 canonical_node_id 从 kt.quant_foundation.position_sizing 调整为 kt.quant_foundation.risk_normalized_metrics。",
    "position_sizing 保留为 related dependency，因为 R-multiple 依赖初始风险单位，但不再作为主分类。",
    "补充 Van Tharp 书籍元数据、SQN/R-multiple distribution 资料和系统交易者 R-multiple/expectancy 资料。",
    "保留边界：R-multiple 只能作为风险归一化复盘、交易结果比较、标签候选和研究评估指标，不能替代成本、滑点、样本外验证、回撤、仓位或风控审计。",
]


def read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object.")
    return payload


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def append_unique_strings(existing: Any, additions: list[str]) -> list[str]:
    values = [str(item) for item in existing if isinstance(item, str)] if isinstance(existing, list) else []
    for addition in additions:
        if addition not in values:
            values.append(addition)
    return values


def next_source_index(item: dict[str, Any]) -> int:
    max_id = 0
    for src in item.get("source_refs", []):
        if not isinstance(src, dict):
            continue
        match = re.search(r"(\d+)$", str(src.get("source_id", "")))
        if match:
            max_id = max(max_id, int(match.group(1)))
    return max_id + 1


def append_source(item: dict[str, Any], raw: dict[str, Any], index: int) -> None:
    refs = item.setdefault("source_refs", [])
    if any(isinstance(src, dict) and src.get("source_url") == raw["source_url"] for src in refs):
        return
    refs.append(
        {
            "source_id": f"src_{index:03d}",
            "source_title": raw["source_title"],
            "source_url": raw["source_url"],
            "source_type": raw["source_type"],
            "publisher": raw["publisher"],
            "published_at": raw["published_at"],
            "accessed_at": TODAY,
            "version": None,
            "reliability": raw["reliability"],
            "score": raw["score"],
            "relevance": "high",
            "freshness": "stable",
            "limitations": raw["limitations"],
            "evidence_summary": raw["evidence_summary"],
            "quoted_excerpt_allowed": False,
        }
    )


def patch_candidate(item: dict[str, Any]) -> dict[str, Any]:
    start = next_source_index(item)
    for offset, source in enumerate(ADDITIONAL_SOURCES):
        append_source(item, source, start + offset)

    classification = item.setdefault("classification", {})
    classification["tree_node_id"] = "kt.quant_foundation.risk_normalized_metrics"
    classification["canonical_node_id"] = "kt.quant_foundation.risk_normalized_metrics"
    classification["tree_path"] = "CEK-TA / Trading Engineering / Quant Foundation / Risk Normalized Metrics"
    classification["subdomain"] = "risk_normalized_metrics"
    classification["claim_type"] = "risk_normalized_metric_definition"
    classification["classification_notes"] = (
        "主归属调整为 kt.quant_foundation.risk_normalized_metrics；R-multiple 是风险单位归一化的交易结果/复盘指标，"
        "position_sizing 只是其初始风险单位依赖，trade_analysis 和 backtest.metrics 是下游使用场景。"
    )
    related = classification.setdefault("related_nodes", [])
    for node in ["kt.quant_foundation.position_sizing", "kt.trade_analysis", "kt.backtest.metrics"]:
        if node not in related:
            related.append(node)

    claim = item.setdefault("claim", {})
    claim["statement"] = (
        "R-multiple 应把单笔交易结果表达为初始风险单位 R 的倍数；它可用于风险归一化复盘、交易结果比较、"
        "标签候选和研究评估，但不能替代交易成本、滑点、样本外验证、回撤、仓位或风控审计。"
    )
    claim["normalized_claim"] = "phase37_r_multiple_as_risk_normalized_metric_with_audit_boundary"
    claim["evidence_summary"] = (
        "Van Tharp 书籍/训练资料、SQN/R-multiple distribution 资料和系统交易者实践资料共同支持 R-multiple "
        "作为 initial-risk-normalized trade outcome metric；CFA execution/risk 来源继续作为成本、执行和风险边界支撑。"
    )
    old_notes = str(claim.get("interpretation_notes", ""))
    claim["interpretation_notes"] = (
        old_notes
        + " 三审补丁：已调整到 risk_normalized_metrics 主节点，并补强书籍、训练、SQN 和系统交易者来源；"
        "本候选仍只是 candidate，不允许 reviewed/approved/default guidance/hard gate。"
    ).strip()

    source_quality = item.setdefault("source_quality", {})
    refs = item.get("source_refs", [])
    primary_types = {"book", "professional_body", "regulatory_guidance", "research_paper", "professional_training_note"}
    source_quality["primary_source_count"] = sum(
        1 for src in refs if isinstance(src, dict) and src.get("source_type") in primary_types
    )
    source_quality["supporting_source_count"] = len(refs) - int(source_quality["primary_source_count"])
    source_quality["score"] = round(
        sum(int(src.get("score", 0)) for src in refs if isinstance(src, dict)) / max(len(refs), 1)
    )
    source_quality["limitations"] = append_unique_strings(source_quality.get("limitations", []), PATCH_NOTES)

    review = item.setdefault("review", {})
    review["open_questions"] = append_unique_strings(
        review.get("open_questions", []),
        [
            "三审是否接受 kt.quant_foundation.risk_normalized_metrics 作为 P37-A-Q02 的主分类？",
            "三审是否认为 Van Tharp 书籍/训练来源、SQN/R-multiple distribution 资料和系统交易者实践资料足以支撑 accepted_for_draft？",
            "正式转换前是否需要人工补充 Super Trader 或 Definitive Guide to Position Sizing 的页码级证据？",
        ],
    )
    review["ai_audit"] = {
        "audit_result_id": "pending_phase37_q02_r_multiple_third_audit",
        "package_id": "phase37_q02_r_multiple_third_audit_package_20260611",
        "decision": "pending_reaudit",
        "reviewed_allowed": False,
        "approved_allowed": False,
        "default_guidance_allowed": False,
        "hard_gate_allowed": False,
        "patch_notes": PATCH_NOTES,
        "boundary": "This third audit package can only decide accepted_for_draft, needs_more_evidence, or rejected.",
    }
    audit_log = review.setdefault("audit_log", [])
    if not isinstance(audit_log, list):
        audit_log = []
        review["audit_log"] = audit_log
    audit_log.append(
        {
            "at": TODAY,
            "actor": "codex",
            "action": "phase37_q02_third_audit_supplemented",
            "reason": "补强 R-multiple 本体来源，并将主分类调整为 risk_normalized_metrics。",
            "audit_result_id": "pending_phase37_q02_r_multiple_third_audit",
        }
    )

    status = item.setdefault("status", {})
    status["review_status"] = "needs_more_evidence"
    status["ingestion_decision"] = "supplemented_for_third_reaudit"
    status["updated_at"] = TODAY
    status["decision_reason"] = "已补强来源和分类，等待三审；仍不是 reviewed/approved/default guidance。"

    workflow = item.setdefault("workflow", {})
    workflow["stage"] = "supplemented_for_third_reaudit"
    workflow["queue_group"] = "needs_more_evidence"
    workflow["next_action"] = "external_ai_or_human_third_reaudit"
    workflow["default_guidance_allowed"] = False
    workflow["approved_allowed"] = False
    workflow["hard_gate_allowed"] = False
    workflow["hidden_from_default_queue"] = True
    workflow["visible_in_default_guidance_queue"] = False

    machine_gate = item.setdefault("machine_gate", {})
    machine_gate["default_guidance"] = "deny"
    machine_gate["reason"] = "candidate still needs third audit; R-multiple is not default guidance."
    machine_gate["requires_human_escalation"] = True

    conflict = item.setdefault("conflict_audit", {})
    conflict["conflict_status"] = "none_known"
    conflict["resolution_summary"] = (
        "No known direct conflict, but P37-A-Q02 remains candidate-only until third audit accepts the stronger sources and risk-normalized metrics classification."
    )
    conflict["default_guidance_allowed"] = False
    conflict["hard_gate_allowed"] = False

    conversion = item.setdefault("conversion_target", {})
    conversion["target_review_status"] = "blocked_until_third_audit"
    conversion["default_guidance_allowed"] = False
    conversion["hard_gate_allowed"] = False
    return item


def has_mojibake(value: object) -> bool:
    return bool(re.search(r"(�|锟|烫|屯|Ã|Â|\?{2,})", json.dumps(value, ensure_ascii=False)))


def quality_gate(item: dict[str, Any]) -> dict[str, Any]:
    failures: list[dict[str, str]] = []
    refs = item.get("source_refs", [])
    classification = item.get("classification", {})
    if len(refs) < 8:
        failures.append({"failure": "source_refs_lt_8"})
    if classification.get("canonical_node_id") != "kt.quant_foundation.risk_normalized_metrics":
        failures.append({"failure": "canonical_node_not_risk_normalized_metrics"})
    if item.get("workflow", {}).get("default_guidance_allowed") is not False:
        failures.append({"failure": "default_guidance_allowed_not_false"})
    if item.get("status", {}).get("ingestion_decision") != "supplemented_for_third_reaudit":
        failures.append({"failure": "not_supplemented_for_third_reaudit"})
    if has_mojibake(item):
        failures.append({"failure": "mojibake_marker_detected"})
    return {
        "report_id": "phase37_q02_r_multiple_third_audit_quality_gate",
        "generated_at": TODAY,
        "candidate_id": item.get("candidate_id"),
        "source_count": len(refs),
        "canonical_node_id": classification.get("canonical_node_id"),
        "failure_count": len(failures),
        "failures": failures,
        "gate_status": "pass" if not failures else "fail",
        "boundary": "candidate-only; no reviewed/approved/default guidance/hard gate.",
    }


def build_audit_package(item: dict[str, Any], quality: dict[str, Any]) -> dict[str, Any]:
    return {
        "package_id": "phase37_q02_r_multiple_third_audit_package_20260611",
        "package_type": "candidate_ai_reaudit_package",
        "schema_version": "1.0.0",
        "generated_at": TODAY,
        "language": "zh-CN",
        "phase": "37",
        "title": "Phase 37 P37-A-Q02 R-multiple 定义三审包",
        "purpose": "严格复审 P37-A-Q02 在补强 R-multiple 本体来源并调整到 risk_normalized_metrics 主分类后，是否可升级为 accepted_for_draft。",
        "strict_boundaries": [
            "candidate 不是正式知识，不能作为默认指导。",
            "三审最多允许 accepted_for_draft，不允许 reviewed、approved、default guidance 或 hard gate。",
            "不得生成买卖点、仓位、杠杆、止损止盈或实盘执行建议。",
            "如果书籍/训练资料、SQN/R-multiple distribution 或分类契约仍不足，必须保持 needs_more_evidence 或 rejected。",
        ],
        "audit_instructions": [
            "必须搜索相关的专业网站、资料、案例和数据，对审计报告进行严格审计。",
            "重点检查 R-multiple 是否被准确限定为 initial-risk-normalized trade outcome metric。",
            "重点检查 kt.quant_foundation.risk_normalized_metrics 是否比 position_sizing 更适合作为主分类；position_sizing 只能作为 related dependency。",
            "检查来源是否足以支撑 accepted_for_draft；若仍缺页码级书籍证据，可要求 formal conversion 前补页码，但不应把 candidate 升级为 reviewed。",
            "输出只能是 accepted_for_draft、needs_more_evidence 或 rejected。",
        ],
        "required_output_schema": {
            "audit_result_id": "string",
            "package_id": "phase37_q02_r_multiple_third_audit_package_20260611",
            "auditor": "string",
            "audited_at": "string",
            "summary": {"total": 1, "accepted_for_draft": 0, "needs_more_evidence": 0, "rejected": 0},
            "candidate_results": [
                {
                    "candidate_id": "cand_20260611_phase37_r_multiple_definition_001",
                    "research_task_id": "P37-A-Q02",
                    "decision": "accepted_for_draft | needs_more_evidence | rejected",
                    "confidence": "low | medium | high",
                    "reviewed_allowed": False,
                    "approved_allowed": False,
                    "default_guidance_allowed": False,
                    "hard_gate_allowed": False,
                    "reasons": ["string"],
                    "required_followups": ["string"],
                    "patch_notes": ["string"],
                }
            ],
        },
        "quality_gate": quality,
        "candidate": item,
    }


def write_research() -> None:
    content = f"""# Phase 37 P37-A-Q02 R-multiple 三审补证记录

生成日期：{TODAY}

## 目标

补齐 `P37-A-Q02 / quant_foundation.r_multiple_definition.v1` 的两个二审阻断点：

```text
1. R-multiple 本体来源不足，不能只依赖 vendor/教育页面。
2. 主分类不应继续放在 position_sizing，应调整为 risk_normalized_metrics，position_sizing 只作为初始风险单位依赖。
```

## 本轮处理

```text
1. 新增 `kt.quant_foundation.risk_normalized_metrics` 知识树三级节点。
2. 将候选 canonical_node_id 改为 `kt.quant_foundation.risk_normalized_metrics`。
3. 补充 Van Tharp 书籍元数据、Position Sizing 书籍元数据、SQN/R-multiple distribution 资料、系统交易者 R-multiple/expectancy 资料和 Van Tharp Institute 训练线索。
4. 保留 candidate-only 边界，不创建 reviewed、approved、default guidance 或 hard gate。
```

## 三审入口

```text
docs/audit/phase37_q02_r_multiple_third_audit_package_20260611.json
```
"""
    RESEARCH_PATH.parent.mkdir(parents=True, exist_ok=True)
    RESEARCH_PATH.write_text(content, encoding="utf-8")


def main() -> None:
    item = patch_candidate(read_json(CANDIDATE_PATH))
    quality = quality_gate(item)
    write_json(CANDIDATE_PATH, item)
    write_json(QUALITY_PATH, quality)
    write_json(AUDIT_PATH, build_audit_package(item, quality))
    write_research()
    report = {
        "report_id": "phase37_q02_r_multiple_third_audit_package_report",
        "generated_at": TODAY,
        "candidate_id": item.get("candidate_id"),
        "research_task_id": item.get("research_task_id"),
        "audit_package": str(AUDIT_PATH),
        "quality_gate": str(QUALITY_PATH),
        "research_record": str(RESEARCH_PATH),
        "source_count": len(item.get("source_refs", [])),
        "canonical_node_id": item.get("classification", {}).get("canonical_node_id"),
        "next_action": "Send the third audit package for strict external AI/human review; do not promote until accepted_for_draft is returned.",
        "boundary": "No formal reviewed knowledge, approved knowledge, default guidance, or hard gate was created.",
    }
    write_json(REPORT_PATH, report)
    if quality["gate_status"] != "pass":
        raise SystemExit(f"quality gate failed: {quality['failures']}")
    print(json.dumps({"candidate_id": item.get("candidate_id"), "source_count": len(item.get("source_refs", [])), "audit_package": str(AUDIT_PATH)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
